### ISSUE TITLE
fluxion can't restart with queues enabled

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#1035]
Problem: If the Fluxion modules are reloaded, and queues are enabled, running jobs will be terminated with the following error (from #991):
```
[  +9.794686] job-manager[0]: scheduler: hello
[  +9.797168] sched-fluxion-qmanager[0]: jobmanager_hello_cb: ENOENT: map::at: No such file or directory
[  +9.797231] sched-fluxion-qmanager[0]: raising fatal exception on running job id=63504667937603584
```

This is using `match-format = "rv1"`

**Comment by grondo** [comment]
I'll see if I can make a standalone reproducer a bit later.

**Comment by trws** [comment]
@grondo, do you happen to have a testcase or reproducer that will produce this, or the original, issue? I'm looking over the code, and I think we must be having an issue with order of init or config or something, because the queue map is definitely populated in the normal path and load order, so something must change when we're in restart that sched doesn't expect.

**Comment by grondo** [comment]
Yes, let me see if I can reproduce this in a test instance.
