### ISSUE TITLE
partial cancel: transition partial cancel final error to warning

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-sched#1309]

**Comment by garlick** [comment]
I guess it's obvious but reducing the log level below LOG_ERR means it won't be seen on the user's stderr.  The bug that was just found and fixed would not have been seen at all since it didn't occur in the node-exclusive configured system instance where logs are persistent.

So good idea/bad idea?  Hmm.

**Comment by milroy** [comment]
The PR I have out to fix issue #1284 and parts of rzadams-related issues demotes the error to a warning since it will be a common occurrence on clusters with `ssd` vertices that aren't attached to a broker rank: https://github.com/flux-framework/flux-sched/pull/1292/commits/6a3eecf9b0a582d0ea78f8da5f3965d9cd4fc047

I can't think of a way to distinguish between a state inconsistency that indicates an error from an inconsistency related to canceling brokerless vertices.

**Comment by milroy** [comment]
@jameshcorbett pointed out that even the LOG_WARNING will fill the logs on systems with rabbits or brokerless ssds. I think this is a compelling argument for making it a LOG_DEBUG.

**Comment by trws** [comment]
This might be a case for keeping the “is it an ssd” check, as a way to say “is this because of rabbits” check just wrapped around the warning message.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by milroy** [comment]
I should add that depending on the pruning filter settings an error/warning/debug may not get logged in this case.

In qmanager, that condition is met when the partial cancels didn't set `full_removal` to be `true`. That can happen if there's some state mismatch between core and fluxion (a true error), or it can happen if brokerless resources are defined in the pruning filters (e.g., `ALL:ssd,All:core`). The pruning filter for `ssd` will cause the partial cancel logic to detect that not all filter resource spans have been removed (hence `full_removal` will be `false`). 

However, if the pruning filter is set to default (`All:core`), if there are brokerless ssds they will get detected by the "is it an ssd" check and the error/warning/debug condition won't be met in qmanager. You may wonder why having additional information in the pruning filter can result in additional work (i.e. the cleanup full cancel) and this logging ambiguity. It's because the cancel traversals are pre-order, so the pruning filter in the `cluster` vertex is checked first.

**Comment by milroy** [comment]
What I could do is add a bool output parameter to `cancel` to indicate whether brokerless vertices were detected. That would allow logging a warning/debug or an error depending on the bool value.

**Comment by milroy** [comment]
@trws: can we close this issue? I think PR #1292 addresses the issue as the final error condition should be encountered rarely and only as a result of a genuine error.

**Comment by trws** [comment]
Yup, I think so.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
