### ISSUE TITLE
t/Makefile.am:17: if $(FLUX_SCHED_TEST_INSTALLED: non-POSIX variable name

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#136]
I'm getting this warning from autoreconf on current master 23ca224e5cbb2b809bbe59be71b8c5ffca3eea6e
```
$ ./autogen.sh
Running autoreconf -i ... 
t/Makefile.am:17: if $(FLUX_SCHED_TEST_INSTALLED: non-POSIX variable name
t/Makefile.am:17: (probably a GNU make extension)
Cleaning up ...
Now run ./configure.

**Comment by garlick** [comment]
```
$ rpm -q autoconf automake libtool
autoconf-2.63-5.1.el6.noarch
automake-1.11.1-4.el6.noarch
libtool-2.2.6-15.5.el6.x86_64
```

**Comment by grondo** [comment]
Hm, sorry for some reason I thought I had read that `$(if ..)` was POSIX, and it was the only sane way I could think of at the time to substitute properly in `TESTS_ENVIRONMENT` for the case where we want to run Lua tests against installed version of flux-sched.

I wonder if, since `TESTS_ENVIRONMENT` is perhaps passed on a command line if we could just do shell substitution there instead of trying to do it in the Makefile? I'm afraid I didn't spend too much time on it, and didn't catch the error...

**Comment by lipari** [comment]
@grondo, I agree that conditionally defining TESTS_ENVIRONMENT in the Makefile.am is a bit awkward unless we craft it to pass unaltered into the final Makefile.  My thought would be to leave the two LUA PATH variables unconditionally defined in the t/Makefile.am and then unset them somewhere in the lua tests if the FLUX_SCHED_TEST_INSTALLED environment variable is defined.  I just have yet to determine the best place for that logic to go.

**Comment by grondo** [comment]
Stay tuned, I'm trying something with POSIX shell substitution that might work.
