### ISSUE TITLE
Faster submit-event handling for high throughput loads

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#185]
This problem was discovered as part of [distribution #14](https://github.com/flux-framework/distribution/issues/14#issuecomment-242176848). To avoid the head-of-line blocking issue caused by high throughput workloads, `sched` needs to optimize ways to handle job creation events: [code](https://github.com/flux-framework/flux-sched/blob/master/sched/sched.c#L1452).

**Comment by garlick** [comment]
Just wanted to point out that the code in `src/modules/kvs/kvs.c` for rate limiting commits might be similar to what you need here.  Look for `min_commit_window` and `commit_timestamp`.

In a nutshell, the heavy weight commit operation is only performed in the message handler for the commit request if `min_commit_window` seconds have elapsed since the last one.  Otherwise the request is queued and a timer is started with a timeout computed so the callback is run `min_commit_seconds` from the previous commit operation.  The timer runs the commit operation (consuming all enqueued commits), disables the timer, and updates the time stamp.

An optimization is to use the (recently added) `flux_reactor_now()` function to get the timestamps, as it saves making a time fetching system call many times in the critical path for precision you don't need.

**Comment by dongahn** [comment]
Thanks @garlick. Yes, this sounds exactly like what I need for this optimization.

**Comment by dongahn** [comment]
@garlick: We chatted about this a bit. A condition that I thought could lead to a deadlock situation with an event-based-only scheme is the following. I am probably too close to the problem so I will appreciate another pair of eyes here:

- a job submitted and the timer is installed
- other jobs are submitted before the timer callback is invoked, but the scheduling for these jobs is delayed
- When the timer expires, `schedule_jobs` will be invoked. But this callback won't be able to iterate through all of the jobs in the pending queue because of the [`queue-depth` optimization] (https://github.com/flux-framework/flux-sched/issues/183#issuecomment-241752491), which we need to limit the overhead of `schedule_jobs.` We could consider context-sensitive queue-depth schemes in which `schedule_jobs` uses essentially unbounded queue depth, but we don't probably want to make it too heavyweight either.

At this point, I wasn't clear what this invoked timer callback has to do. It can install the timer again, but then when the callback is invoked again, it seems the callback wants to perform some state check whether the queue state has changed or not. I thought about a couple of ways to do a state check (e.g., job count, etc), but none of them was a correct solution but an approximation.

The timer callback could simply not install the new timer. But then if a corner case arises and there will be no further new job submit event , the jobs in the pending may not be scheduled, leading to a deadlock. 

So at that point, my brain started to hurt and I thought a traditional timer-based solution is needed anyway...

**Comment by garlick** [comment]
Note that flux-framework/flux-core#788 changed the commit aggregation algorithm described above.  Sorry, moving target!

I think under a high submit load, to avoid missing high priority messages like job state change events, you'll need to find a way to triage incoming messages very quickly, getting them out of the way of other messages in the message queue.  I would guess without invoking `schedule_jobs`, your one thread should be able to keep up with the rate jobs can be enqueued, given that _those_ are throttled by other services like the KVS and the job submission service.

If you are able to keep up, then you could actually use the same algorithm used by the KVS, where the commit processing is deferred until all the currently pending messages are handled.  This is just like GUI programming, where key press events are all handled before the screen update.  (In fact that is a use case that drives support for this pattern in libev).

I don't know exactly how the scheduler internals work but if the fast triage can track if any running jobs changed state since the last `schedule_jobs`, or if jobs were added to the queue "below" the cutoff depth, then if one or both of those is true, you could run `schedule_jobs` after all events are processed, otherwise simply block for new messages, because the scheduler won't be considering any new information.

If the scheduler thread cannot keep up and `schedule_jobs` gets starved by the triage, then some more logic might be needed to cause `schedule_jobs` to be invoked early.  For example, during triage, if the above conditions are met but `schedule_jobs` hasn't been run for some configurable time, run it right then.

**Comment by garlick** [comment]
By the way if the above looks like a promising approach, see this commit to KVS: flux-framework/flux-core@b6524ea9ec1b2927ce464ae24f2ab9597da8e06f

**Comment by dongahn** [comment]
> Note that flux-framework/flux-core#788 changed the commit aggregation algorithm described above. Sorry, moving target!

Thanks. I will take a look. 

> I think under a high submit load, to avoid missing high priority messages like job state change events, you'll need to find a way to triage incoming messages very quickly, getting them out of the way of other messages in the message queue. I would guess without invoking schedule_jobs, your one thread should be able to keep up with the rate jobs can be enqueued, given that those are throttled by other services like the KVS and the job submission service.

Agreed.

> If you are able to keep up, then you could actually use the same algorithm used by the KVS, where the commit processing is deferred until all the currently pending messages are handled. This is just like GUI programming, where key press events are all handled before the screen update. (In fact that is a use case that drives support for this pattern in libel).

Yes, deferred scheduling is an optimization technique we absolutely need one way or the other. 

> I don't know exactly how the scheduler internals work but if the fast triage can track if any running jobs changed state since the last schedule_jobs, or if jobs were added to the queue "below" the cutoff depth, then if one or both of those is true, you could run schedule_jobs after all events are processed, otherwise simply block for new messages, because the scheduler won't be considering any new information.

This is a good point @garlick! It will be difficult for a timer callback itself alone to decide if the pending job queue state has changed since it was invoked last time, but perhaps it is possible if we add a simple infrastructure into the scheduler's job queue implementation...

Enqueue/dequeue operations that lead to a change in the queue's position between 1 and `queue-depth` would arm the timer (if there is no existing timer)... If we directly build this into our queue, then we don't have to spread this logic across many different places in the scheduler code (e.g., resource event handler, job handler, later job prioritization...). The only thing is if we can do this very quickly such that the performance of normal enqueue/dequeue won't be affected much... 

>If the scheduler thread cannot keep up and schedule_jobs gets starved by the triage, then some more logic might be needed to cause schedule_jobs to be invoked early. For example, during triage, if the above conditions are met but schedule_jobs hasn't been run for some configurable time, run it right then.

My hope is we don't have to do this :-)

**Comment by garlick** [comment]
Great!  No timer needed if you take the approach referenced above - the reactor does the work for you.  It sounds like the tricky part will be deciding if you need to run `schedule_jobs` or not.  Your prep and check callbacks would need to both be able to test for that, so ideally some flag is set during the "triage" period and cleared when `schedule_jobs` is finally run.

**Comment by dongahn** [comment]
@garlick: 

> No timer needed if you take the approach referenced above - the reactor does the work for you. It sounds like the tricky part will be deciding if you need to run schedule_jobs or not. 

Oh. That'd be better. You make me want to look at your code now :-)

> It sounds like the tricky part will be deciding if you need to run schedule_jobs or not. 

Yes, and do this in a future proof fashion -- there will be lots of code that will affect this algorithm (e.g., job shuffling through prioritization etc...) and I want to isolate this logic as much as possible.
