### ISSUE TITLE
t2002-easy.t runs jobs out of order

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-sched#214]
As discussed in #212, t2002-easy.t was failing and subsequently disabled (temporarily).
Needs some investingation

```
expecting success: 
	flux module load sim exit-on-complete=false

ok 1 - loading sim works

expecting success: 
	flux module load submit job-csv=${jobdata}

ok 2 - loading submit works

expecting success: 
	flux module load sim_exec

ok 3 - loading exec works

expecting success: 
	flux module load sched rdl-conf=${rdlconf} in-sim=true plugin=sched.backfill plugin-opts=reserve-depth=1

ok 4 - loading sched works

expecting success: 
    diff -u ${expected_order} ./actual

--- /home/garlick/proj/flux-sched/t/data/emulator-data/easy_expected	2016-01-26 23:30:14.551980905 +0000
+++ ./actual	2016-10-13 23:34:10.653669158 +0000
@@ -1,12 +1,12 @@
 1
 2
 3
+4
+5
 6
 7
 8
 9
 10
 11
-4
-5
 12
not ok 5 - jobs scheduled in correct order
#	
#	    diff -u ${expected_order} ./actual
#	

# failed 1 among 5 test(s)
1..5
```

This started failing reliably at the same time as the JSON changes in flux core.

See also:

#212
#210
flux-framework/flux-core#835
flux-framework/flux-core#849

**Comment by lipari** [comment]
Preliminary indications are that the simulated jobs are completing immediately.  Hence the jobs are scheduled/completed in the order of submission.  Still studying...

**Comment by garlick** [comment]
Just curious - does this test still fail on @grondo's branch with the jansson conversion?

**Comment by lipari** [comment]
Sorry to report that, yes it did.

**Comment by SteVwonder** [comment]
Sorry guys for not responding sooner.  I need a few days to wrap up our IPDPS paper, but after that, this will be my number 1 priority.

**Comment by SteVwonder** [comment]
Just popping in to say that I am currently looking into this problem (I haven't forgotten).  It looks like the `sim_exec` module is failing at pulling job information from the KVS.   The data is being correctly parsed by the `submit` module and the data does make it into the KVS correctly (I dump the relevant values at the end of the simulation and they are correct).  For some reason, during the simulation, `sim_exec` fails to pull the data from the KVS.  I will continue my investigation after dinner tonight.

**Comment by SteVwonder** [comment]
So I think I have isolated the issue, and if I am correct, the problem lies with the new JSON library.
I pushed my reproducer to [this branch](/SteVwonder/flux-sched/tree/sim-json-repro).  A log from this version can be found [here](https://gist.github.com/SteVwonder/00a84f2c29139e0fea54a66d895a3a0c). You can reproduce the same errors by directly runnning [`t2002-easy.t`](https://github.com/SteVwonder/flux-sched/blob/sim-json-repro/t/t2002-easy.t).

In [`put_job_in_kvs`](https://github.com/SteVwonder/flux-sched/blob/sim-json-repro/simulator/simulator.c#L140), the simulator is storing additional data about a particular job that is necessary for the simulation. One such item being `submit_time`, which is stored using `kvsdir_put_double`.  When the simulator goes to retrieve that variable using `kvsdir_get_double` in the [`pull_job_from_kvs`](https://github.com/SteVwonder/flux-sched/blob/sim-json-repro/simulator/simulator.c#L188) function, it fails (returns -1).  If you dump the job's kvs directory using the command line, the data is there.  Oddly enough though, there is no fractional component, it is printed as an integer.  Surely enough, when `submit_time` is retrieved with `kvsdir_get_int`, it succeeds (see [here](https://github.com/SteVwonder/flux-sched/blob/sim-json-repro/simulator/simulator.c#L227)).

So my initial conclusion is that the new JSON library is serializing the double without the fractional component.  Thus, when the value is deserialized the inferred type is an int.  This bad inference then causes [this check](https://github.com/flux-framework/flux-core/blob/master/src/modules/kvs/libkvs.c#L1535) to fail (which is supported by strerr producing  "Protocol error" after the failure).

Does this sound right to others?  If so, how should we go about fixing it?

**Comment by grondo** [comment]
Wow, good find @SteVwonder! Sounds like we have a simple reproducer too, thanks! I'll try reproducing and also make a standalone test we can add to the testsuite

**Comment by grondo** [comment]
Hm, though interestingly I don't think the libkvs calls were updated to the new JSON library so this may require some investigation

**Comment by SteVwonder** [comment]
@grondo: good call.  It might just be the addition of that strict check for type `double` (added in [this commit](https://github.com/flux-framework/flux-core/commit/fc905eedb4b5ffca25bfba308a994037cc7814f6)).  I would presume for any `_get_double` type functions, we would want to allow for the underlying type to be an int and then just upcast to a double.  Rather than checking is the type is `json_type_double`, can we check for something like `json_type_number` (if that exists).

**Comment by SteVwonder** [comment]
Looks like we could just call `json_object_get_double` directly and check if `value == 0.0 && errno == EINVAL`. [source](https://github.com/json-c/json-c/blob/818156f6f79c1c34e6e596798822846bcaea7b9f/json_object.h#L776)

**Comment by grondo** [comment]
@SteVwonder, good find that may be it though I would have thought if you serialize JSON as a double then json_type_double() should return true on the object after it is parsed, but this could easily be a json-c shortcoming. Sounds like the solution you propose is a pretty good one, though I'd like to hear @garlick's comment.

**Comment by garlick** [comment]
Ah, yes good sleuthing there.  I'm a bit uncomfortable with 0.0 as an error return value.  What if that's the actual value, then if normal POSIX errno semantics are used, errno would be invalid.  Coercing values other than integer seem pretty useless.  How about this instead?
```diff
diff --git a/src/modules/kvs/libkvs.c b/src/modules/kvs/libkvs.c
index efcb79e..0f27f68 100644
--- a/src/modules/kvs/libkvs.c
+++ b/src/modules/kvs/libkvs.c
@@ -512,7 +512,8 @@ int kvs_get_double (flux_t *h, const char *key, double *val)
 
     if (getobj (h, NULL, key, 0, &v) < 0)
         goto done;
-    if (json_object_get_type (v) != json_type_double) {
+    if (json_object_get_type (v) != json_type_double
+            && json_object_get_type (v) != json_type_int) {
         errno = EPROTO;
         goto done;
     }

```

**Comment by grondo** [comment]
I still don't understand why `Jtostr (json_object_new_double (1.0))` is incorrectly serializing `1.0` to an int `1`, or even where this is happening. `flux kvs put foo=1.0 && flux kvs type foo` returns `double`...
I think there is some other weirdness going on here because these values should be serialized to double, even if they can be represented as integers.

**Comment by SteVwonder** [comment]
@grondo: agreed.  [This comment](https://github.com/json-c/json-c/blob/master/json_object.c#L716) makes me think that the intended functinality is to have at least one trailing zero when serializing a double.  In addition, it doesn't seem like their testsuite ever explicitly tests a put operation on a double with no fractional component.  So it's hard to see exactly what the intended behavior is.

FWIW, in [this reproducer](https://github.com/SteVwonder/flux-core/blob/json-types-test/src/common/libutil/test/jsontypes.c) the double type sticks with the value before serialization but is lost after serialization.  So the bug is probably located somewhere in the json-c (de-)serialization code.

Should we open an issue over in the json-c repo?

**Comment by grondo** [comment]
Yeah, the problem is that json-c double-to-json-string function is using "%g" format which drops all zeros if possible (they using "%.17g" specifically). I'll let @garlick summarize further.

**Comment by garlick** [comment]
Right.  Since the JSON spec only defines a "number" type, the serialization of 1.0 as 1 is technically correct and so I think just applying the change proposed above to the kvs is the right approach rather than trying to fix json-c.  Want to submit PR for that?

@SteVwonder: since you took the trouble to create the gist with standalone reproducer, why don't you go ahead and open a json-c issue.  It sounds like this was not their intent so they may appreciate it.

**Comment by grondo** [comment]
We should add test to the kvs that if you `kvs_put_double()` an integer, you can get it back out as a double.

**Comment by grondo** [comment]
BTW, the documentation for "%g" says:

```
              Trailing zeros are removed from
              the  fractional part of the result; a decimal point appears only
              if it is followed by at least one digit.

```

So the fact that the json-c code then goes through and attempts to remove trailing zeroes by hand does seem to indicate the use of `"%g"` here is not intentional.

**Comment by SteVwonder** [comment]
Ah! That makes sense.

Ok.  I can submit a PR and open an issue.

**Comment by grondo** [comment]
Thanks for figuring this one out @SteVwonder

**Comment by SteVwonder** [comment]
@grondo: I believe the loop that attempts to remove the trailing zeros is there in the case that the user supplies their own format string.  (Although the implementation could be optimized by skipping that loop if the default format string is used).

**Comment by grondo** [comment]
Ah, ok sorry I didn't look carefully enough!
