### ISSUE TITLE
Create job priority plugin

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-sched#282]
Before retirement, @lipari began creating a flux job priority plugin.  His work-in-progress is shared in pull request #275.  This issue will track the further work needed to complete the plugin.

Useful information:

* [Job Priority Plugin Implementation Notes](../wiki/Job-Priority-Plugin-Implementation-Notes)
* [Note About The Flux Fair Share Algorithm](../wiki/Note-About-The-Flux-Fair-Share-Algorithm)

**Comment by SteVwonder** [comment]
Just wanted to document the unresolved discussion that @morrone brought up at the end of today's meeting: how to calculate the cost/usage for an arbitrary tree of resources. (@morrone: if you want this in a separate ticket, just let me know and I'll move it).

My summary/elaboration of one of the suggestions:  the cost calculation could simply be another function exposed by the priority plugin. The functions takes a resource tree (i.e., the resources allocated to a given job) and returns a numerical "cost" for that set of resources.  To replicate the current SLURM functionality, we could take @nedbass's suggestion and just count the core-hours being allocated.  Then, if we decide to start charging for reads/writes to the local SSDs, on Catalyst for example, we could implement a more complex plugin that includes this into its calculations.  Presumably this function would run when the job starts, so as to include the expect usage in future fair-share calculations, and then again when the job completes, to ensure that the recorded usage is 100% accurate (e.g., a job might exit before its walltime is up, and you can't know the reads/writes to the local SSD apriori).

The obvious pro to this approach is that it is extensible to arbitrary resource sets and to users' whims.  

The cons (as @morrone pointed out) are:
- The priority plugin now needs to pull in the resrc library to traverse resource trees
- User intervention/coding is required for any cost calculations beyond what we provide

Does anyone have other suggestions for what this interface should look like or how this should be implemented?  Any other pros/cons to this suggested solution?

**Comment by grondo** [comment]
Sorry if I quite likely missed something obvious, but could you guys explain why the cost calculation belongs in the priority plugin, instead of in a separate "cost" or utilization plugin? Is it because the main (only?) user of the data (besides upper mgmt) is the priority plugin?

**Comment by dongahn** [comment]
@grondo: good point. I think we can introduce a new module or plugin to dump the multi-resource usage information into a common store which then gets used by the priority plugin. The scheme can be similar to [#116](https://github.com/flux-framework/rfc/issues/116).

I think what @SteVwonder proposes above is reasonable. If we used a common store approach, I don't worry too much about the priority plugin access the resource trees. (cuz, it won't)

It seems the only thing is for the case where a job has multiple resources allocated, some of which has different life spans. (e.g., Cray data wrap has this persistent BB allocation mode). Once we ultimately introduce our grow/shrink functionality, this scheme can be directly applied to such a case as well though.

**Comment by morrone** [comment]
I think that flux sched proper probably needs to implement the usage tracking for a job.  After all, something like a "reservation" _might_ (depending on how they are implemented in the particular scheduler) not actually instantiate any resource usage that the resource management components in flux core would know about.  Nevertheless, we probably want to charge the user/account for the entire reservation time, even when they are not running jobs.  They are still monopolizing the system and preventing others from running jobs.

**Comment by dongahn** [comment]
@morrone: Interesting. Even if a reservation is cancelled, some usage should incur because the fact that we had that reservation may have slowed down scheduling some jobs. This would be ideal; I am just not sure how sophisticated we can be in this case... Maybe, some constant factor * the size of the reservation. 

In general, R used in an allocation/reservation and the actual (not requested) duration of this would probably be the general case. Then, different types of resources may incur different usage costs, we need an interface to calculate usage as a programmable weighted sum over multiple resources. Still a plugin into sched can collect this info and dump it to a common store.

**Comment by morrone** [comment]
> Even if a reservation is cancelled, some usage should incur because the fact that we had that reservation may have slowed down scheduling some jobs.

You are talking about cancelling a job before its start time?  Sure, that has scheduling impact closer to the start time, but I'm not sure that we would institutionally decided to charge the account for time before its start.

_After_ the reservation starts, it should probably be charged for the entire time.  Unless perhaps standby jobs are allowed to run when nothing is run by the users of the allocation...then maybe the standby job usage would be subtracted?  I guess it all comes down to policy preference at some point.

**Comment by dongahn** [comment]
> After the reservation starts, it should probably be charged for the entire time. Unless perhaps standby jobs are allowed to run when nothing is run by the users of the allocation...then maybe the standby job usage would be subtracted?

Yes, this would be the general case, and this shouldn't be so different than an allocation case perhaps except for standby. Well a reservation in a sense is an allocation in the future time anyway.

>  I guess it all comes down to policy preference at some point.

Agreed. This should be a site configurable and I guess we need to factor this into our interfaces...

**Comment by morrone** [comment]
I have been contemplating the idea from our team meeting on Monday to run the algorithm through the simulator. 

We need to ask ourselves what we are trying to test, and how we will know from the results if we pass or not.  If we want to test the algorithm just to see if it restricts usage to the allocated shares over a long period of time, then using real-world data probably isn't the best plan.  Real-world data is not evenly distributed, so we wouldn't expect the result to exactly match the share implied percentages.

If we want to just test long term percentage distribution to validate application of shares, we should probably have a large set of equal sized jobs always in the queue from all possible user/account combinations in the configuration.  But that isn't necessarily very useful either.

The long-term distribution is the easy thing to get right, and pretty easy to validate through analysis of the algorithm, actually running the simulation wouldn't help our understanding.  Targeted testing and simulation still server a purpose, for instance helping to verify that the _implementation_ matches the design.

Where the the three candidate algorithms (slurm fair-share, slurm fair-tree, and Don's modified fair-tree) differ most significantly, I think, is in the _short term_ decision making about the ordering of jobs that are close in priority.  The fair-share algorithm has some obvious deficiencies, and we are planning to replace that with fair-tree in production anyway, so we can largely ignore fair-share as a candidate for the first flux priority algorithm.

So that leaves comparing fair-tree and Don's modified fair-tree.  And as I said, using a real-world data set simulation at this early stage of development probably does not help shed useful light on the problem.

Instead we need to scrutinize the algorithms and look for what happens when those algorithms are combined with other multi-factor weightings, and see how the corner cases behave.  Those details are hard to mine from a large simulation.

Further, the large simulation won't really reflect what we will see in the real world until more development is done in flux.  Most significantly we are missing usage decay, which will no doubt significantly impact a large dataset simulation.

So I am planning to _not_ immediately pursue the simulation plan with real-world data (unless someone can make a good argument for what we would learn right now).  Instead, I plan to continue like so:

- Continue analysis of the algorithms.  In particular, learn how the fair-tree rankings are combined with other weighting factors.  For Don's algorithm, do some math to see whether lower levels of the tree will have a large enough impact to correctly steer priority ordering of near-priority jobs versus weighting factors like queue time.  (The biggest difference between fair-tree and Don's modified fair-tree is that fair-tree has consistent integer spacing between all ranks, whereas the modified fair-tree has variable fractional spacing.)

- Continue development of the plugin: functional improvements, test infrastructure, design/improve usage tracking and querying interfaces with other flux components, implement usage decay, allow refreshing of share configuration (currently statically read at startup), etc.

**Comment by dongahn** [comment]
@morrone: I was also wondering about this after our meeting Monday. I believe your short term plan makes sense to me.

> Continue analysis of the algorithms. In particular, learn how the fair-tree rankings are combined with other weighting factors. For Don's algorithm, do some math to see whether lower levels of the tree will have a large enough impact to correctly steer priority ordering of near-priority jobs versus weighting factors like queue time. (The biggest difference between fair-tree and Don's modified fair-tree is that fair-tree has consistent integer spacing between all ranks, whereas the modified fair-tree has variable fractional spacing.)

I am more than willing to be a sounding board for your algorithm analysis. I think we can get pretty good mileage out of this. 

I will ask this to @tpatki and @SteVwonder, though. You are our scheduling research experts by now. What are the best practices and general methodology that scheduling research community is using to evaluate the fairness of job scheduling algorithms?

**Comment by SteVwonder** [comment]
After doing a quick literature search on `fairness` in batch job scheduling (JSSPP papers are great for this), it seems that the term `fairness`, as used by the community, is much broader than just fairness between users.  In the literature, `fairness` extends to all features of a job.  So in many papers, a scheduling algorithms that is biased towards small jobs is "unfair". In this context, the community has no standard definition of `fairness`: https://link.springer.com/chapter/10.1007/978-3-642-35867-8_13.  So really, I think it is up to each facility to determine the dimensions of fairness that are important to them.

In the context of this discussion (and Livermore Computing), we are focusing on fairness across users. More specifically, that each users gets access to the percentage of the system that they were promised, without being starved out by other users with lower priorities.  `Fair share` is a keyword that gets closer to what we are looking for.

So for our purposes, it seems that a simple sum of squared residuals/error (SSR/SSE) will suffice.  Specifically comparing the percentage of the cluster provided to each user against the promised percentage of the cluster (for some fixed time interval): ![equation](https://i.imgur.com/ISqEzuG.png).  

Where `rm(t)` is the total amount of computing resource allocated to all the jobs from account `m` during time `t`, `R(t)` is the total available computing resource during time `t`, and `γm≥0` is the weighting parameter indicating the desire amount of resource allocation to account `m`. The fairness score is maximized when `rm(t)=γmR(t)` for `m=1,2,⋯,M`. A contextualized version of the equation can be found in this paper: http://ieeexplore.ieee.org/document/6257975/

**Comment by springme** [comment]
+ Greg and Ryan since this discussion may be of interest to them.

Sent from my iPhone

On Dec 1, 2017, at 12:12 PM, Stephen Herbein <notifications@github.com<mailto:notifications@github.com>> wrote:


After doing a quick literature search on fairness in batch job scheduling (JSSPP papers are great for this), it seems that the term fairness, as used by the community, is much broader than just fairness between users. In the literature, fairness extends to all features of a job. So in many papers, a scheduling algorithms that is biased towards small jobs is "unfair". In this context, the community has no standard definition of fairness: https://link.springer.com/chapter/10.1007/978-3-642-35867-8_13. So really, I think it is up to each facility to determine the dimensions of fairness that are important to them.

In the context of this discussion (and Livermore Computing), we are focusing on fairness across users. More specifically, that each users gets access to the percentage of the system that they were promised, without being starved out by other users with lower priorities. Fair share is a keyword that gets closer to what we are looking for.

So for our purposes, it seems that a simple sum of squared residuals/error (SSR/SSE) will suffice. Specifically comparing the percentage of the cluster provided to each user against the promised percentage of the cluster (for some fixed time interval): [equation] <https://camo.githubusercontent.com/fda1b9d06e52911a80c0c6c1bf6165849f98ed23/68747470733a2f2f692e696d6775722e636f6d2f495371457a75472e706e67> .

Where rm(t) is the total amount of computing resource allocated to all the jobs from account m during time t, R(t) is the total available computing resource during time t, and γm≥0 is the weighting parameter indicating the desire amount of resource allocation to account m. The fairness score is maximized when rm(t)=γmR(t) for m=1,2,⋯,M. A contextualized version of the equation can be found in this paper: http://ieeexplore.ieee.org/document/6257975/

**Comment by dongahn** [comment]
OK. We also discussed what it means to be fair in the presence of multiple resource types. As a food for thoughts, here is a reference to `dominant resource fairness (DRF)` that cloud computing guys are using, I was talking about: https://cs.stanford.edu/~matei/papers/2011/nsdi_drf.pdf

If you don't want to read this entire paper, I believe Section 4 describes the gist of it.

For us, we will probably need to introduce a vector of shares, each representing the share of an account for a resource type, instead of a singleton scalar share.

**Comment by dongahn** [comment]
This is not handled through flux-accounting.
