### ISSUE TITLE
sim: run a simulation under valgrind as part of test suite

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#332]
Building off of #328 (thanks @grondo for the excellent addition!), I think we should run the simulator under Valgrind as part of the test suite.  This should help solve #288 and pre-empt issues like the ones addressed in #289.

**Comment by grondo** [comment]
Good idea @SteVwonder. I was wondering while working on this if it would be useful to support adding additional valgrind workloads via a `valgrind/valgrind-workload.d` directory (one test workload per script in that directory). One drawback of this approach is that flux bootstrap is slow under valgrind, and these tests would all run serially. Therefore, it might be more efficient to add additional commands to the existing `valgrind-workload.sh` when possible. We could add `workload-pre.d`, `workload-post.d` and `workload.d` directories to allow drop-in extensions to the "basic" workload if that would help.

**Comment by dongahn** [comment]
I would also like to hook valgrid tests for resource-query as well but this will need a new test in t5000.

**Comment by SteVwonder** [comment]
I like the idea of the `valgrind-workload.d` directory. For the workloads in that directory, would each workload be run in the same Flux instance, one after another?  Or would each workload bootstrap an instance?  If they are each bootstrapping an instance, why can't we execute them in parallel?  

I also like the idea of merging workloads as much as possible to avoid the bootstrap cost.  The merging solution should work for a lot of cases.  I can't say that I have ever tried to run the simulator after having run real jobs in the Flux instance.  I will have to give that a try.

**Comment by grondo** [comment]
>   If they are each bootstrapping an instance, why can't we execute them in parallel?

Because of the way the sharness tests work with parallel `make check` the easiest way to run tests in parallel is to have separate sharness test files, e.g. `t5000-valgrind.t` `t5001-valgrind-sim.t` etc. Then the level of parallelism is controlled by `make -j N` and automake parallel-tests.

That isn't to say we couldn't parallelize within `t5000-valgrind.t`, but it would then be a little kludgy -- you might have to do something like run valgrinds in parallel, issue a wait for all valgrinds to complete, collect exit status from each under `test_expect_success` and output logfile on failure. (actually, it doesn't sound impossible now that I write it down) However, you'd want to be able to control the level of parallelism because some test platforms perhaps can't take 2 or more valgrind sessions running at once (I'm thinking of Travis-CI and/or c9.io)

**Comment by grondo** [comment]
closed by #440.
