### ISSUE TITLE
Do not emit rank.N dirs in kvs for wreck jobs

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-sched#338]
Now that we have `R_lite` the `rank.N` dirs generated in the kvs are no longer used.
If sched avoids creation of these dirs, it will save a lot of extra kvs traffic, especially for large jobs.

In flux-core, support for these dirs as fallback will be removed.

**Comment by dongahn** [comment]
Yes, good idea. Let me see if I can quick add this into the current PR (#333).

**Comment by dongahn** [comment]
Looking at the code, `rank.N` has GPU support while `R_lite` does not...

Maybe @trws uses `rank.N` to determine the number of GPUs being allocated. I will defer this work in my current PR until I hear more.

**Comment by trws** [comment]
I extended the former because that’s what sched was producing. Whatever we use needs to support it, but honestly I forgot to do that since R_lite was essentially unused.


---
Sent from VMware Boxer

On May 4, 2018 at 8:00:26 PM PDT, Dong H. Ahn <notifications@github.com> wrote:

Looking at the code, rank.N has GPU support while R_lite does not...

Maybe @trws<https://github.com/trws> uses rank.N to determine the number of GPUs being allocated. I will defer this work in my current PR until I hear more.

**Comment by dongahn** [comment]
#339 resolved this issue.
