### ISSUE TITLE
flux-sched command

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#361]
Per @grondo in #337:

> The `flux wreck` command is going away in the near future. At some point the flux-sched project will want to install its own utility -- perhaps a `flux sched <command>`? (I think flux-core exports liboptparse so that development of the subcommand should be trivial)

This command will at least support the functionality already (or soon to be) in `flux wreck`:

- changing scheduler parameters at runtime
- including/excluding nodes

**Comment by tpatki** [comment]
Another functionality is for adding/removing power, in order to convey changes in global or system power budgets resulting from grid fluctuations. This will also address some of the initial issues with dynamic power-aware scheduling that were noted earlier, maybe with a simple plugin that bypasses jobspec's power bound but uses the overall system budget to allocate power to jobs without user input.

**Comment by tpatki** [comment]
@dongahn: Is it ok for me to work on this issue next?

**Comment by dongahn** [comment]
Yes, this will be fine. But I think we can wait a bit until the other execution system development come along because some co-design will be needed, i suspect.

**Comment by dongahn** [comment]
Now we have the new execution system completed, we should start a discussion for this co-design.

**Comment by dongahn** [comment]
The first codesign discussion is scheduled on 10/22.

**Comment by dongahn** [comment]
This is duplicate: Issue #556
