### ISSUE TITLE
sched's Travis build fails after pmix update

### ISSUE THREAD

**Issue by tpatki** [flux-framework/flux-sched#364]
Travis build for sched fails, probably because libevent-dev (required by pmix) is missing. 

```
============================================================================
== Libevent
============================================================================
checking for libevent in... (default search paths)
looking for header in /usr/include
checking event.h usability... no
checking event.h presence... no
checking for event.h... no
looking for header in /usr/include/include
checking event.h usability... no
checking event.h presence... no
checking for event.h... no
configure: WARNING: LIBEVENT SUPPORT NOT FOUND
configure: error: CANNOT CONTINUE
make: *** No targets specified and no makefile found.  Stop.
travis-dep-builder.sh: Failed to build and install pmix-3.0.0
```

**Comment by tpatki** [comment]
Thanks, @grondo! Yes, I added it to the sched PR @dongahn will merge soon.

**Comment by tpatki** [comment]
@grondo: I added `libevent-dev` to apt-packages (which is what Travis was complaining about), I think it uses it for the build in the `before-install` section. Should I add `pmix-dev`instead?

**Comment by garlick** [comment]
I don't think there is a pmix-dev apt package.  If there is, silly me, I
built it on the side for flux core.

**Comment by grondo** [comment]
> @grondo: I added libevent-dev to apt-packages (which is what Travis was complaining about), I think it uses it for the build in the before-install section. Should I add pmix-devinstead?

Sorry no, that was just a typo on my part!

**Comment by garlick** [comment]
Sorry for creating this problem (and not anticipating it)!

**Comment by dongahn** [comment]
@garlick, @grondo : BTW, one thing I don't fully understand. For the future reference, are we supposed to list all of the package dependencies for flux-core in flux-sched's Travis config file as well?

**Comment by grondo** [comment]
Typically yes, since we're building flux-core as a dependency of flux-sched, we will need all the dependent packages as well as other deps built from `travis-dep-builder.sh` for now.

This case was a weird one, though. The version of flux-core built for flux-sched doesn't actually use --with-pmix, however `travis-dep-build.sh` still tries to build pmix, so the *pmix* dependencies were needed, even though that package wasn't actually used.

We can do better, but this is what we have for now...

**Comment by tpatki** [comment]
@dongahn: The travis script for flux-sched first builds flux-core (calls the core's travis-dep-builder.sh), so I believe we need to list all dependencies. I am wondering if there was a way to to include the dependencies in [flux-core/src/test/travis-dep-builder.sh](https://github.com/flux-framework/flux-core/blob/master/src/test/travis-dep-builder.sh) instead of sched?

**Comment by grondo** [comment]
> I am wondering if there was a way to to include the dependencies in flux-core/src/test/travis-dep-builder.sh instead of sched?

Since it is a travis-specific script, and we're currently running travis with `sudo: true`, we could `sudo apt-get install <deps>` in there. However, that would mean we *must* continue running with `sudo: true` instead of using `.travis.yml` for package management.

Ideally we will eventually build `flux-sched` from flux-core tags and the package requirements will be static (until it is time to transition flux-sched to a new tag of flux-core)
