### ISSUE TITLE
General solution to use shared_ptr directly for callback architecture

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#538]
This is created from a discussion in PR #537. 

In our offline discussion @trws proposed a generic wrapper that translates `share_ptr` to `void *` in a more robust and safer manner and this issue is created to track that proposal.

**Comment by trws** [comment]
The main thing would be avoiding things like this:

```c++
ctx = *(static_cast<std::shared_ptr<qmanager_ctx_t> *>(arg));
```

Instead have the object inherit from `enable_shared_from_this` and either just
use the pointer directly, or if you need to keep a reference to it for ownership
use `shared_from_this`.  So, basic version:

```c++
struct my_type : std::enable_shared_from_this<my_type> {
  // stuff
};

void bar(void *meh) {
  my_type *a = dynamic_cast<my_type *>(meh);
  a->do_stuff_with_a();
  if(need_to_keep_ownership_of_a()){
    std::shared_ptr<my_type> a_sp = a->shared_from_this();
    store_shared_ptr(a_sp);
  }
}

void foo() {
  auto a = std::make_shared<my_type>();
  bar(a.get());// get pointer out, std compatible way
}
```


This avoids holding a pointer to a shared_ptr, which is a really easy way to end
up with a dangling reference that's hard as heck to debug.  It's not necessarily
wrong, it's just really really easy to make a mistake with (I say this with many
sad weeks of nasty debugging caused by making the mistake myself... it's not
fun).

**Comment by trws** [comment]
I just noticed your comment on the other ticket @dongahn.  This won't solve the ownership issue, there still needs to be a live shared_ptr somewhere to keep the thing alive, probably in the ctx I guess or something else managed as part of the lifetime of the module.  There are a number of ways to deal with that, but this doesn't directly deal with that so much as it deals with passing the thing around through C code.

**Comment by dongahn** [comment]
> I just noticed your comment on the other ticket @dongahn. This won't solve the ownership issue, there still needs to be a live shared_ptr somewhere to keep the thing alive, probably in the ctx I guess or something else managed as part of the lifetime of the module. There are a number of ways to deal with that, but this doesn't directly deal with that so much as it deals with passing the thing around through C code.

The owership isn't an issue for now. I passed the shared_ptr whose life time is the mod_main.

**Comment by dongahn** [comment]
@trws: thanks again Tom. I think the issue is the function that takes in `void *` isn't my C++ function but C function provided by flux so I can't use the technique like you suggest.

**Comment by dongahn** [comment]
> This won't solve the ownership issue

```c++
void bar(void *meh) {
  my_type *a = dynamic_cast<my_type *>(meh);
  a->do_stuff_with_a();
  if(need_to_keep_ownership_of_a()){
    std::shared_ptr<my_type> a_sp = a->shared_from_this();
    store_shared_ptr(a_sp);
  }
}
```

Just out of curiosity: once you get to `std::shared_ptr<my_type> a_sp = a->shared_from_this();` statement, you created an another shared owner, so even if the other owner goes out of scope, this object won't be destroyed?

**Comment by dongahn** [comment]
Maybe for the current code where I have no control over the function that takes in `void *` -- e.g., `flux_set_aux`, I just pass the raw pointer of the `shared_ptr` object using `.get ()` method and when I get the pointer back in `getctx`, use this `std::enable_shared_from_this` trick to use shared_ptr more safely. 

Or now that I think about this, it may be best to just ditch `shared_ptr` for `resource_ctx_t` and `qmanager_ctx_t` piece as they need to go through `void *` of flux-core's C APIs and this may not really warrant the use of shared pointers... 

My goal was to remove raw pointers as much as possible. But maybe our good old raw pointers still have places in the real world where C and C++ need to co-habitate.

**Comment by trws** [comment]
> @trws: thanks again Tom. I think the issue is the function that takes in `void *` isn't my C++ function but C function provided by flux so I can't use the technique like you suggest

This comment confuses me. Why can’t you use it? The entire point is that you pass a regular pointer through the void* just like C, if anything it makes the types more C-like, but lets you get the C++ context back on the other side. 

Seeing your newer comment I think you’re probably right about the context, the shared_ptr probably really doesn’t help for those two. It would help for anything with multiple owners though, which is why this comes up:

> Just out of curiosity: once you get to `std::shared_ptr<my_type> a_sp = a->shared_from_this();` statement, you created an another shared owner, so even if the other owner goes out of scope, this object won't be destroyed?

That’s exactly right, and it’s the real reason to do this. For example, if you add some data to a node in the resource graph in a traversal, and want to keep another reference to it in a map during the traversal through a c callback or something, this way you can get another reference to keep it alive from just a pointer to the object itself.

**Comment by dongahn** [comment]
> This comment confuses me. Why can’t you use it? The entire point is that you pass a regular pointer through the void* just like C, if anything it makes the types more C-like, but lets you get the C++ context back on the other side.

Yes, you are absolutely right. I was initially confused that you were proposing a new void * function. But it does make sense to cast the raw pointer back when it comes to the C land. 

So was my newer comment: https://github.com/flux-framework/flux-sched/issues/538#issuecomment-543440314

> Seeing your newer comment I think you’re probably right about the context, the shared_ptr probably really doesn’t help for those two. It would help for anything with multiple owners though, which is why this comes up:

Indeed, this task started as I had some serious multiple owner case.

**Comment by dongahn** [comment]
I will decide whether I want to pursue `shared_from_this` or not tomorrow with fresh eyes. On one hand, shared pointer doesn't add much for those main module contexts. But it may be worthwhile having some of these examples for future C++ users.
