### ISSUE TITLE
configure: support using auto-detected flux-core installation when installing to a different prefix

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#611]
Per a coffee discussion, it would be nice if `$HOME/opt/flux-core/bin/flux env ./configure —prefix=$HOME/opt/flux-sched` worked. Now that #603 is in, we are most of the way there. We need to fallback to the flux binary’s prefix when the user-specified prefix doesn’t contain the libraries we are looking for (or something along those lines).

**Comment by grondo** [comment]
Hm, after #603 `AX_FLUX_CORE` takes the following steps:

 1. prepends `${prefix}/lib/pkgconfig` to `PKG_CONFIG_PATH` and checks for `flux-core` so that, by default, we find the same `flux-core` as the destination prefix configured for flux-sched
 2. sets `FLUX_PREFIX` to the prefix of the libflux-core found in step 1.
 3. sets `FLUX` to the first `flux` binary in `$FLUX_PREFIX/bin:$PATH` to ensure `FLUX` points to the same `flux(1)` binary as corresponds to the libflux-core found int step 1, 
 4. Finds the other `libflux-*` libraries while `PKG_CONFIG_PATH` is still prepended

In your use case above, the system-installed flux-core will be found first by `PKG_CHECK_MODULES([FLUX_CORE], [flux-core], ...)` since the target flux-core is side-installed, but not in the same `--prefix` as flux-sched. Therefore, currently you need to set `PKG_CONFIG_PATH` by hand in order to make this installation work.

Perhaps a simple approach would be to prepend `current_flux_prefix/lib/pkgconfig` to `PKG_CONFIG_PATH` *first*, _then_ prepend `PREFIX/lib/pkgconfig`, which as you say will fall back to finding libflux-core associated with the first `flux` found in path, not the first found in the system `PKG_CONFIG_PATH`.

e.g., try this:
```diff
diff --git a/config/ax_flux_core.m4 b/config/ax_flux_core.m4
index 014a6d6..fd66fed 100644
--- a/config/ax_flux_core.m4
+++ b/config/ax_flux_core.m4
@@ -53,11 +53,23 @@
 #
 
 AC_DEFUN([AX_FLUX_CORE], [
-  # prepend PREFIX/lib/pkgconfig to PKG_CONFIG_PATH.
-  # Allows flux-core in the destination PREFIX to be found by pkg-config
-  #  by default, assuming in 99% of cases this is what we want.
+  # Find the *current* path to flux executable before checking for
+  # libflux-core with pkg-config.
+  AC_PATH_PROG(current_flux_path, [flux])
+  if test -n "$current_flux_path"; then
+      current_flux_prefix=`AS_DIRNAME(["$current_flux_path"])`
+      current_flux_prefix=`AS_DIRNAME(["$current_flux_prefix"])`
+  fi
 
+  # Prepend PREFIX/lib/pkgconfig to PKG_CONFIG_PATH,
+  # followed by PREFIX/lib/pkgconfig of the current flux(1) binary
+  # found in PATH
+  #
+  # Checks for libflux-core first in destination PREFIX, falling back
+  # to PREFIX of the current flux, finally falling back to system
+  # installed flux:
   saved_PKG_CONFIG_PATH=$PKG_CONFIG_PATH
+  PKG_CONFIG_PATH=${current_flux_prefix}/lib/pkgconfig:${PKG_CONFIG_PATH}
   PKG_CONFIG_PATH=${prefix}/lib/pkgconfig:${PKG_CONFIG_PATH}
   export PKG_CONFIG_PATH
```

**Comment by dongahn** [comment]
This is in now.
