### ISSUE TITLE
Need temporal allocations in resrc

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-sched#62]
@lipari, already has the idea sketched out (which he shared with @surajpkn and I).
My summary from our short meeting is:
*  Expand the `resrc_allocate` and `resrc_release` functions to include a start and end time
  * Either (or both) of these times could be -1, meaning infinity
* Include a function that allows you to determine if a resource is allocated at a particular time
  * This would perform an intersection check for every allocation

**Comment by surajpkn** [comment]
@lipari please feel free to delegate any part of the implementation to me. Since I cannot really proceed to implement the dynamic scheduling without the above, I can work on parts myself too (if it wouldn't really require too much of background knowledge on what you already did or is easy to catch up on).

**Comment by SteVwonder** [comment]
I would also offer my help, but I will be unavailable next week.  So if this still needs work after next week, I can jump in and help too.

**Comment by lipari** [comment]
First off, this issue seems to reflect the needs first described in [Issue 25](https://github.com/flux-framework/flux-sched/issues/25).

Adding time to the resource model has a potential of becoming complicated unless we can think of a means to restrict the requirements or simplify the design.

Starting with the basics as laid out in [RFC 4](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc), any resource allocated to a job needs to be annotated with that job's id.  A more significant complication is the hierarchical nature of the composite resource pool also from RFC 4.  That RFC calls for annotating the resource with not only a job it is allocated to, but the job id's of all ancestors.

This was the mechanism we devised to allow a scheduler to determine whether any given resource could be allocated exclusively to a job.  E.g., if a "rack" resource was mostly idle, but there was one job running on one core on one node of the rack, that job id would be annotated at the rack level, and all intervening resources down to the core itself.  A scheduler in this example could tell that the rack could not be allocated to a job that requested exclusive access to a rack.

The "allocs" and "reservtns" members of the resrc structure were intended to implement this design.  These two members were intended to capture all the job's that were either allocated to the resource or had a reservation on the resource.

The first enhancement to this initial implementation was the size component.  In theory, every resource has a size, and that size is nominally one.  A memory resource for example could have a size of 32 for every GB of memory we can individually allocate to a job.  Hence, the model should eventually (it does not now) support the ability to assign 8 "size" units to job 5 while simultaneously allocating 16 units to job 17.

On top of all of this, we need to add the time element.  It essentially combines all of the constructs above, with snapshots of every point in time when any job begins or ends, or some resource within the hierarchy is added or removed.

Anyway, the above is a summary of my thinking on this issue and a brief status on the plans for the design.

**Comment by SteVwonder** [comment]
Thanks Don.  These are good points.

If you could insert both "exclusive" and "shared" allocations into the interval tree, that would seem to solve the hierarchical issue.  For example, when a core is exclusively allocated for 1 hour, insert an "exclusive" allocation (of size 1 for 1 hour) in the core resource, and then a "shared" allocation (of size 1 for 1 hour) in all ancestors of that core.  Then if you want to exclusively allocate a rack, you check for a range overlap between your wanted allocation and all the existing allocations for the rack (both shared and exclusive).   The problem then becomes, we have optimized for the operation "give me an exclusive allocation on resource A" (where resource A is towards the root of the hierarchy) and made expensive the operation "give me an allocation on resource B" (where resource B is towards the bottom of the hierarchy).

**Comment by SteVwonder** [comment]
Also, should we close this issue and move the discussion to #25?

**Comment by lipari** [comment]
I preferred the opposite.  I just closed Issue 25, directing the reader to this Issue.

**Comment by lipari** [comment]
[PR 66](https://github.com/flux-framework/flux-sched/pull/66) added the time dimension to the resource model.  Hence, I am closing this issue.  The secondary request for shared and exclusive access has been opened as a separate [Issue 101](https://github.com/flux-framework/flux-sched/issues/101)
