### ISSUE TITLE
[feedback] semantics of queuing policies under resource.acquire

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#670]
Problem: the definition of a backfill queuing policy is that you can backfill a later job as far as it does not delay the start time of an earlier job. Under `resource.acquire` (or any real system where resources are going up and down), however,  some modifications to the backfill definition seems necessary. 

Here are modification options that I can think of. Any feedback welcome.  

1. Reject the earlier job when it cannot get its start time guarantee and allocate the later job. This is against what we have been discussing and seems to have usability concerns. 

2. Don't backfill any later job if the earlier job cannot get its starttime guarantee due to "down" resources. We don't reject the earlier job because it is still satisfiable if those resources were up; at the same time, since we can't give the starttime guarantee either, we don't backfill. This seems pedantic to the traditional definition (an arguably fairer) but seems pretty inefficient. 

3. Just skip past the earlier job (but don't reject it) and backfill later jobs. This would be efficient but can have a fairness question (in particular if "down" resources quickly come back up).

Since no matter what we do, we seem to have to make a trade off. My currently thinking is # 3. Are there any other cool options? 

Now that I think about this, the same question arise there with FCFS too. If the earlier job cannot run because of "down" resources, what do we do there? Maybe we should be more strict in this case. The users' workload may have more strict ordering requirements... We may instead offer another queuing policy (backfill w/ reservation depth=0) when users don't require strict fcfs ordering.

**Comment by SteVwonder** [comment]
> Under resource.acquire (or any real system where resources are going up and down), however, some modifications to the backfill definition seems necessary.

This is a really good point.  I agree that most (all?) backfill algorithms out right now can only make reservation guarantees under the assumption that nodes don't go up/down.  I hadn't thought of that before.

In your hypothetical scenario, is the "earlier job" here so large as to be unschedulable while a single node is down (e.g., it's a whole system job), or are there other nodes on the system that the job could be switched to (although it may have to wait for those nodes to free up)?  In the former case, yeah, that is a tricky one.  I agree that scenario 3 seems like the best way forward.  For the latter, I think a modified version of scenario 3, where you make a new reservation rather than skipping the job, is the way to go.  The job's reservation time may jump further into the future in this case, but given the node failure, I don't think that is always avoidable.

**Comment by SteVwonder** [comment]
> For the latter, I think a modified version of scenario 3, where you make a new reservation rather than skipping the job, is the way to go. The job's reservation time may jump further into the future in this case, but given the node failure, I don't think that is always avoidable.

I don't know that this technique exists in any production schedulers currently, but if the "DOWN" state is estimated to be resolvable with a node reboot (e.g., the node OOM'd or some driver was hung), then maybe the scheduler should not try and find a whole new set of nodes for the job, and instead wait a configurable amount of time to see if the node reboot puts the node into the "UP" state (and then add the appropriate time onto the backend of the job's existing reservation).  Just a half-baked thought for now.

**Comment by grondo** [comment]
Maybe a dumb idea, but could some investigation be done here using the simulator?

**Comment by garlick** [comment]
> if the "DOWN" state is estimated to be resolvable with a node reboot (e.g., the node OOM'd or some driver was hung), then maybe the scheduler should not try and find a whole new set of nodes for the job

Just as a data point, I _think_ our admins require a human to intervene before a node that's hung or crashed or rebooted itself is made available to users again.  Depending on their perception of the urgency, a node might not bounce right back into service.

**Comment by dongahn** [comment]
> In your hypothetical scenario, is the "earlier job" here so large as to be unschedulable while a single node is down (e.g., it's a whole system job), or are there other nodes on the system that the job could be switched to (although it may have to wait for those nodes to free up)? In the former case, yeah, that is a tricky one.

Yeah, former.

**Comment by dongahn** [comment]
>> For the latter, I think a modified version of scenario 3, where you make a new reservation rather than skipping the job, is the way to go. The job's reservation time may jump further into the future in this case, but given the node failure, I don't think that is always avoidable.

Yeah, I don't see any problem with this case. This complies with the original definition and fairness guarantee of backfill policies. 

> I don't know that this technique exists in any production schedulers currently, but if the "DOWN" state is estimated to be resolvable with a node reboot (e.g., the node OOM'd or some driver was hung), then maybe the scheduler should not try and find a whole new set of nodes for the job, and instead wait a configurable amount of time to see if the node reboot puts the node into the "UP" state (and then add the appropriate time onto the backend of the job's existing reservation). Just a half-baked thought for now.

I think this will be difficult to implement. "down" event is a resource state changing event and the "plan" has to be newly built...

**Comment by dongahn** [comment]
> Just as a data point, I think our admins require a human to intervene before a node that's hung or crashed or rebooted itself is made available to users again. Depending on their perception of the urgency, a node might not bounce right back into service.

Yap. And when those nodes are brought into service and `resource` acquire responds, fluxion will be able to make use of it to build a new "plan" possibly making the job's start time estimate earlier.

**Comment by SteVwonder** [comment]
> could some investigation be done here using the simulator?

Definitely!  I think this would be a good approach.  We could start by simulating nodes going up and down and quantify the amount of fairness "lost" due to job reservations being delayed, and quantify how much improvement we stand to gain by improving this algorithm.  (Obviously a longer term plan for post initial rollout).

Shorter-term, I really should get that simulator PR rebased and into master so that we can leverage it to test functionality when nodes go up/down. It's on my TODO list for other reasons, it just hasn't bubbled to the top.

**Comment by dongahn** [comment]
This was implemented as part of PR #667.
