### ISSUE TITLE
flux-tree: redirect stdio streams

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-sched#691]
It would be nice to be able to redirect the stdio streams of each `flux tree` leaf instance to different files. I was thinking maybe providing some kind of format string on the command line that gets formatted when each leaf instance is created? Since `flux tree` already uses Python-style `"{}".format()` formatting, maybe something like `flux tree -T2x2 --stdout my_logs_{tree_id}.log --stderr my_errs_{tree_id}.log` which would yield files `my_logs_tree.1.1.log` and so on.

**Comment by dongahn** [comment]
This is great idea @jameshcorbett! I thought about this but didn't know what would be a great way to achieve this. But your suggestion makes a lot of sense. 

I won't be able to get this right away though because of other priorities. I will add "help wanted" label for now. If we don't get help we circle back to this after our milestones.
