### ISSUE TITLE
Issues with launching MuMMI 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#729]
Another issue related to Issue #728:

> Relatedly, we’ve been running into some interesting behavior regarding running ddcMD – the behavior is characterized by the following:
> 1. The workflow manager schedules a ddcMD job, and it fails.
> 2. We grab the rank it’s on and find its hostname with “flux exec” and ssh into the node. From here, we launch ddcMD how it would be expected to launch with an explicit “flux mini run …” and it starts up.
> 3. We interrupt the command, and attempt to relaunch it again – except this time, flux tells us it can’t find the path “/var/tmp” and the execution fails.
 
> We’re unsure what’s causing that behavior, but I did notice that MPI enabled codes that were compiled without the shim modules would fail when attempted to be run under a Flux instance (I discovered this with Maestro testing using the LULESH proxy app). We have a hypothesis that maybe this unexpected behavior may be due to ddcMD being compiled outside our loaded environment without knowledge of the shim modules; we’ll confirm that shortly. We wanted to float this by you as it’s urgent that we be able to run repeatedly, especially as we look at rolling ddcMD under our analysis process to recover from failures. Attached is a screenshot from a run Harsh started tonight – as you can tell, he’s added the “hostname” command followed by a call to our script for launching ddcMD on 4 patches. As you can see, the first time the host name prints and ddcMD starts, but after a user interrupt and a resubmit via “flux mini run” not even the host name is printed. Any insight that you might be able to provide would be valuable as we’re currently sitting with one hypothesis with no other leads at the moment.

**Comment by dongahn** [comment]
@FrankD412: I think I need some clarification to characterize the issue here. 

> 2. We grab the rank it’s on and find its hostname with “flux exec” and ssh into the node. From here, we launch ddcMD how it would be expected to launch with an explicit “flux mini run …” and it starts up.

What is this node? From 1. `ddcMD` job failed, so it is not clear what node. 

Is the `ddcMD` job is launched within a nested instance and are you trying to get inside that instance?

**Comment by FrankD412** [comment]
Alright -- sorry about the delay, power outages and other things managed to keep me from posting; it looks like we got this sorted out. I think in a previous instantiation we may have wrapped the `ddcMD` jobs in wrapper scripts in order to get the naming the way we wanted. Those may have included brokers, but I honestly couldn't tell you at this point it was long enough ago. I had initially thought that the `flux mini run` calls would be caught by the master broker on the node, but that doesn't appear to be the case. Once we scheduled under a broker, `ddcMD` successfully ran and was named appropriately with my recent changes to Maestro's Flux adapter -- so that now gets rid of the middle man wrapper script.

We did in the course of figuring this out run into our Flux instance telling us that requests made with GPUs were unsatisfiable. We're currently unsure if this is an installation issue or a bigger issue. @SteVwonder recommended starting a new issue for that error.

**Comment by SteVwonder** [comment]
Thanks @FrankD412!  I'll go ahead and close this issue then.

**Comment by dongahn** [comment]
Thanks. 

> We did in the course of figuring this out run into our Flux instance telling us that requests made with GPUs were unsatisfiable. 

Yes we want to look at your jobspec for this again.

**Comment by FrankD412** [comment]
> Thanks.
> 
> > We did in the course of figuring this out run into our Flux instance telling us that requests made with GPUs were unsatisfiable.
> 
> Yes we want to look at your jobspec for this again.

Sounds good -- I'll mover over to #728
