### ISSUE TITLE
Grow with RV1/JGF reader

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#767]
@grondo, @garlick,  @SteVwonder and @milroy:

At our coffee hour discussion yesterday (https://github.com/flux-framework/flux-core/issues/3228#issuecomment-712471059), I said we will need a new JGF reader to support the embedded full rv1 object. 

I realized I mispoke. Looking at the code, our JGF reader will work just fine to create a new graph data store from the embedded R. 

This should be a matter of changing the reader from hwloc reader to JGF reader at https://github.com/flux-framework/flux-sched/blob/master/resource/modules/resource_match.cpp#L549!

But to enable the "grow" case (needed to cover the resources that are "unexcluded" at runtime), we still need to implement the `unpack_at ()` method within our JGF reader would do the bulk lifting. (It is currently `ENOTSUP`). 

My current guess is to add code to support rv1/JGF reader should be much smaller than I initially thought. (https://github.com/flux-framework/flux-sched/blob/master/resource/readers/resource_reader_jgf.cpp#L806)

So the initial step I would like to take:
-  add initial bootstrapping support within Fluxion to reads in RV1/JGF in a nested instance from the parent. This may help investigate the resource ID consistency better.

**Comment by milroy** [comment]
I implemented `unpack_at ()` for the dynamic resources paper; you can find it in my dev branch [here](https://github.com/milroy/flux-sched/blob/683b7841cb41c6837c4f86e0d1ec2349afd0782d/resource/readers/resource_reader_jgf.cpp#L1011).

I am concerned that my implementation is fragile, because it assumes certain structure in the JGF subgraph.  In particular, the vertices must be traversed in reverse level order to guarantee correct [`grow` behavior](https://github.com/milroy/flux-sched/blob/683b7841cb41c6837c4f86e0d1ec2349afd0782d/resource/readers/resource_reader_jgf.cpp#L520).  This wasn't an issue for my research work, but probably isn't desirable for production.

**Comment by milroy** [comment]
@dongahn can we make any assumptions about the JGF subgraph (i.e., it will contain a path to the cluster root)?

**Comment by dongahn** [comment]
@milroy: 

Are you asking if each vertex in a JGF subgraph must have a path or a JGF subgraph should be a complete graph with our supported topology? At first glance, it seems we need both?

**Comment by milroy** [comment]
Good question, I should have been more detailed.  What I meant was if the JGF subgraph is transformed to an undirected graph by replacing all directed edges with undirected edges, can we assume each vertex has a path to the cluster root in the JGF subgraph?  This isn't quite the same thing as a complete graph, where every pair of vertices has an undirected edge.

**Comment by milroy** [comment]
After my conversation with @dongahn this week, I've implemented what I think is a robust `unpack_at` procedure.  We will require that every JGF subgraph is fully qualified, meaning that in undirected form (or for the containment subsystem, where each pair of adjacent vertices has an `in` and `contains` edge) every vertex has a path to the cluster root.

We can't make any assumptions about the order of vertices and edges in the JGF subgraph, so we can't assume any iteration order in [`unpack_vertices`](https://github.com/flux-framework/flux-sched/blob/07ec55fb728ad260ffb25834ba48a66dbd5275cc/resource/readers/resource_reader_jgf.cpp#L530).  This means we need to "verify" the integrity of the subgraph before adding it to the resource graph, because we need to determine which vertices and edges to add (some, like the root, will already exist in the resource graph).  So there's a two-step process: create a boost subgraph, and then iterate through the vertices and edges to add the new structure.  I've created an [`unpack_at ()`](https://github.com/milroy/flux-sched/blob/bcf8c80feaf783195a982f70bea6ffeb795245f2/resource/readers/resource_reader_jgf.cpp#L918) in my fork, which I've confirmed works as expected with my research `grow`.  I created some auxiliary functions like `copy_vtx` to copy boost vertex properties from the subgraph vertex to the resource graph vertex.

Once the RV1/JGF reader is in place I can adapt the code from my fork and make a PR.

**Comment by dongahn** [comment]
Yes this sounds really good @milroy. I would encourage you to think if there are ways to add some unit tests; or use `resource query` to do most of testing.

**Comment by milroy** [comment]
Sure thing; I'll get to work on unit tests!

**Comment by milroy** [comment]
@dongahn after further thought I came up with a way to add the JGF subgraph without creating an intermediate boost subgraph.  You can take a look at the new [`unpack_at ()`](https://github.com/milroy/flux-sched/blob/31d2d01896fa71a32d38109ce814933dbc169e37/resource/readers/resource_reader_jgf.cpp#L955) in my fork.

**Comment by milroy** [comment]
I should add that I've tested the latest implementation with my research `grow` and confirmed that it works as expected.  I'll come up with some test cases to make sure that the implementation handles malformed and unordered JGFs.

**Comment by dongahn** [comment]
@milroy: This sounds promising. We should compare our notes soon. Good luck on your Q&A today!

**Comment by dongahn** [comment]
PR #787 has this support.
