### ISSUE TITLE
qmanager: urgency -> priority

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-sched#798]
While working on a `flux-sched` fixup for https://github.com/flux-framework/flux-core/issues/3450, I noticed that in some locations the variable `urgency` is used when it should be `priority`.

for example

```
    if (schedutil_alloc_request_decode (msg, &job->id, &job->urgency,
                                        &job->userid, &job->t_submit) < 0) {
        flux_log_error (h, "%s: schedutil_alloc_request_decode", __FUNCTION__);
        return;
    }
```

The function `schedutil_alloc_request_decode` returns a job priority, not a job urgency.

I was going to make a change through, but the maximum urgency appears to be hard coded in for "priority" calculations.

```
    // Note that RFC27 defines 31 as the max urgency. Because our queue policy
    // layer sorts the pending jobs in lexicographical order
    // (<urgency, t_submit, ...> and lower the better, we adjust the urgency.
    job->urgency = 31 - job->urgency;
```

so I was a little reluctant to make this change at the moment.

perhaps this will all go away once a priority plugin is developed, but thought I should atleast document this.

**Comment by dongahn** [comment]
The term changed from priority to urgency actually recently ( https://github.com/flux-framework/flux-sched/pull/781). If the range of the priority changed and documented in a RFC, it would be okay to revert the name to priority and increase the hard coded value.

BTW, the main reason to do this smallest to largest convergence is so that we could just use default ordering of `std::map`. We could also add a custom comparator to reverse or customize the ordering logic.

**Comment by chu11** [comment]
ok, just didn't know if the hard coded 31 had meaning or not.

**Comment by dongahn** [comment]
Yeah it is the MAX priority previously defined in an RFC.
