### ISSUE TITLE
Change the default match policy to "first match"?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#827]
Since the first match is a lot faster and most of our current users require high throughput mode, perhaps we should consider changing the default match policy to first match? Any thoughts?

**Comment by SteVwonder** [comment]
> Any thoughts?

Seems like a good idea.  Since our current default match policy is `high`, I don't think users will notice much of a difference.  I think the only visible change will be the spreading of jobs across nodes rather than packing jobs into the lowest ID nodes, right?

Sort of related side-note: Jeff, Frank, and I found the "high ID" first behavior confusing when debugging things the other day.  Assigning GPU 1 and then GPU 0 is counter-intuitive.  If we can flip the tie breaker to go to lower ID resources in `first match`, I think that will be useful to users.

**Comment by dongahn** [comment]
> Seems like a good idea. Since our current default match policy is high, I don't think users will notice much of a difference. I think the only visible change will be the spreading of jobs across nodes rather than packing jobs into the lowest ID nodes, right?

Yes. Also for system-instance, we will want to implement better "locality" and set that as our policy through a yet-to-come config file anyway.

**Comment by dongahn** [comment]
> Sort of related side-note: Jeff, Frank, and I found the "high ID" first behavior confusing when debugging things the other day. Assigning GPU 1 and then GPU 0 was counter-intuitive to us. If we can flip the tie breaker to go to lower ID resources in first match, I think that will be useful to users.

You will need "low ID" first instead then. Oh I will add a caveat to my posting above. First match policy does the tie breaking based on "uniq_id" which is under `hwloc` reader mode is identical to vertex index. So whichever GPU reported by hwloc in our hwloc reader walk will determine this...
