### ISSUE TITLE
GitHub action: Upload tarball fails

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-sched#832]
![Screen Shot 2021-05-05 at 10 36 41 PM](https://user-images.githubusercontent.com/862123/117247053-787bc400-adf2-11eb-9632-aef25e24a31c.png)

**Comment by grondo** [comment]
Sorry @dongahn, this is a known problem. For some reason `make dist` doesn't produce a correctly versioned tarball in the GitHub Action for a tag. I haven't gotten to the bottom of it yet, so I've just been running `make dist` myself and editing the release to upload the tarball.

It is slightly tricky to test this without tagging, but maybe I can use my own fork (or a fake project) to get to the bottom of this one.

**Comment by dongahn** [comment]
Ah. Ok. I will manually upload the tarball myself. Thanks!

**Comment by dongahn** [comment]
Done!

**Comment by grondo** [comment]
Ok, I think I've found the problem, as have many others in this issue https://github.com/actions/checkout/issues/290

The fix is to either revert to `checkout@v1`, or to add `git fetch -f origin ${{ github.ref }}:${{ github.ref }}` when the action is running on a tag. (I'll submit a PR with the second approach for flux-core and flux-sched)
